/**
 * Project: lifeplanner-webapp
 * File: layout
 * Created by pennycodes on 10/08/2023.
 * Copyright lifeplanner-webapp
 */

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function Layout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return children;
}
